# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/barth/projets_epitech/tek3/c++/tmp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/barth/projets_epitech/tek3/c++/tmp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/barth/projets_epitech/tek3/c++/tmp/CMakeFiles /home/barth/projets_epitech/tek3/c++/tmp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/barth/projets_epitech/tek3/c++/tmp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server_automoc

# Build rule for target.
server_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server_automoc
.PHONY : server_automoc

# fast build rule for target.
server_automoc/fast:
	$(MAKE) -f CMakeFiles/server_automoc.dir/build.make CMakeFiles/server_automoc.dir/build
.PHONY : server_automoc/fast

#=============================================================================
# Target rules for targets named client_automoc

# Build rule for target.
client_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client_automoc
.PHONY : client_automoc

# fast build rule for target.
client_automoc/fast:
	$(MAKE) -f CMakeFiles/client_automoc.dir/build.make CMakeFiles/client_automoc.dir/build
.PHONY : client_automoc/fast

client_automoc.o: client_automoc.cpp.o

.PHONY : client_automoc.o

# target to build an object file
client_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_automoc.cpp.o
.PHONY : client_automoc.cpp.o

client_automoc.i: client_automoc.cpp.i

.PHONY : client_automoc.i

# target to preprocess a source file
client_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_automoc.cpp.i
.PHONY : client_automoc.cpp.i

client_automoc.s: client_automoc.cpp.s

.PHONY : client_automoc.s

# target to generate assembly for a file
client_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client_automoc.cpp.s
.PHONY : client_automoc.cpp.s

server_automoc.o: server_automoc.cpp.o

.PHONY : server_automoc.o

# target to build an object file
server_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_automoc.cpp.o
.PHONY : server_automoc.cpp.o

server_automoc.i: server_automoc.cpp.i

.PHONY : server_automoc.i

# target to preprocess a source file
server_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_automoc.cpp.i
.PHONY : server_automoc.cpp.i

server_automoc.s: server_automoc.cpp.s

.PHONY : server_automoc.s

# target to generate assembly for a file
server_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server_automoc.cpp.s
.PHONY : server_automoc.cpp.s

src/Client/QtBabel/BabelClient.o: src/Client/QtBabel/BabelClient.cpp.o

.PHONY : src/Client/QtBabel/BabelClient.o

# target to build an object file
src/Client/QtBabel/BabelClient.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/BabelClient.cpp.o
.PHONY : src/Client/QtBabel/BabelClient.cpp.o

src/Client/QtBabel/BabelClient.i: src/Client/QtBabel/BabelClient.cpp.i

.PHONY : src/Client/QtBabel/BabelClient.i

# target to preprocess a source file
src/Client/QtBabel/BabelClient.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/BabelClient.cpp.i
.PHONY : src/Client/QtBabel/BabelClient.cpp.i

src/Client/QtBabel/BabelClient.s: src/Client/QtBabel/BabelClient.cpp.s

.PHONY : src/Client/QtBabel/BabelClient.s

# target to generate assembly for a file
src/Client/QtBabel/BabelClient.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/BabelClient.cpp.s
.PHONY : src/Client/QtBabel/BabelClient.cpp.s

src/Client/QtBabel/Event.o: src/Client/QtBabel/Event.cpp.o

.PHONY : src/Client/QtBabel/Event.o

# target to build an object file
src/Client/QtBabel/Event.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Event.cpp.o
.PHONY : src/Client/QtBabel/Event.cpp.o

src/Client/QtBabel/Event.i: src/Client/QtBabel/Event.cpp.i

.PHONY : src/Client/QtBabel/Event.i

# target to preprocess a source file
src/Client/QtBabel/Event.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Event.cpp.i
.PHONY : src/Client/QtBabel/Event.cpp.i

src/Client/QtBabel/Event.s: src/Client/QtBabel/Event.cpp.s

.PHONY : src/Client/QtBabel/Event.s

# target to generate assembly for a file
src/Client/QtBabel/Event.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Event.cpp.s
.PHONY : src/Client/QtBabel/Event.cpp.s

src/Client/QtBabel/Message.o: src/Client/QtBabel/Message.cpp.o

.PHONY : src/Client/QtBabel/Message.o

# target to build an object file
src/Client/QtBabel/Message.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Message.cpp.o
.PHONY : src/Client/QtBabel/Message.cpp.o

src/Client/QtBabel/Message.i: src/Client/QtBabel/Message.cpp.i

.PHONY : src/Client/QtBabel/Message.i

# target to preprocess a source file
src/Client/QtBabel/Message.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Message.cpp.i
.PHONY : src/Client/QtBabel/Message.cpp.i

src/Client/QtBabel/Message.s: src/Client/QtBabel/Message.cpp.s

.PHONY : src/Client/QtBabel/Message.s

# target to generate assembly for a file
src/Client/QtBabel/Message.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/Message.cpp.s
.PHONY : src/Client/QtBabel/Message.cpp.s

src/Client/QtBabel/QtCircularBuffer.o: src/Client/QtBabel/QtCircularBuffer.cpp.o

.PHONY : src/Client/QtBabel/QtCircularBuffer.o

# target to build an object file
src/Client/QtBabel/QtCircularBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtCircularBuffer.cpp.o
.PHONY : src/Client/QtBabel/QtCircularBuffer.cpp.o

src/Client/QtBabel/QtCircularBuffer.i: src/Client/QtBabel/QtCircularBuffer.cpp.i

.PHONY : src/Client/QtBabel/QtCircularBuffer.i

# target to preprocess a source file
src/Client/QtBabel/QtCircularBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtCircularBuffer.cpp.i
.PHONY : src/Client/QtBabel/QtCircularBuffer.cpp.i

src/Client/QtBabel/QtCircularBuffer.s: src/Client/QtBabel/QtCircularBuffer.cpp.s

.PHONY : src/Client/QtBabel/QtCircularBuffer.s

# target to generate assembly for a file
src/Client/QtBabel/QtCircularBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtCircularBuffer.cpp.s
.PHONY : src/Client/QtBabel/QtCircularBuffer.cpp.s

src/Client/QtBabel/QtGui.o: src/Client/QtBabel/QtGui.cpp.o

.PHONY : src/Client/QtBabel/QtGui.o

# target to build an object file
src/Client/QtBabel/QtGui.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtGui.cpp.o
.PHONY : src/Client/QtBabel/QtGui.cpp.o

src/Client/QtBabel/QtGui.i: src/Client/QtBabel/QtGui.cpp.i

.PHONY : src/Client/QtBabel/QtGui.i

# target to preprocess a source file
src/Client/QtBabel/QtGui.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtGui.cpp.i
.PHONY : src/Client/QtBabel/QtGui.cpp.i

src/Client/QtBabel/QtGui.s: src/Client/QtBabel/QtGui.cpp.s

.PHONY : src/Client/QtBabel/QtGui.s

# target to generate assembly for a file
src/Client/QtBabel/QtGui.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtGui.cpp.s
.PHONY : src/Client/QtBabel/QtGui.cpp.s

src/Client/QtBabel/QtNet.o: src/Client/QtBabel/QtNet.cpp.o

.PHONY : src/Client/QtBabel/QtNet.o

# target to build an object file
src/Client/QtBabel/QtNet.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtNet.cpp.o
.PHONY : src/Client/QtBabel/QtNet.cpp.o

src/Client/QtBabel/QtNet.i: src/Client/QtBabel/QtNet.cpp.i

.PHONY : src/Client/QtBabel/QtNet.i

# target to preprocess a source file
src/Client/QtBabel/QtNet.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtNet.cpp.i
.PHONY : src/Client/QtBabel/QtNet.cpp.i

src/Client/QtBabel/QtNet.s: src/Client/QtBabel/QtNet.cpp.s

.PHONY : src/Client/QtBabel/QtNet.s

# target to generate assembly for a file
src/Client/QtBabel/QtNet.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtNet.cpp.s
.PHONY : src/Client/QtBabel/QtNet.cpp.s

src/Client/QtBabel/QtUdpSocket.o: src/Client/QtBabel/QtUdpSocket.cpp.o

.PHONY : src/Client/QtBabel/QtUdpSocket.o

# target to build an object file
src/Client/QtBabel/QtUdpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtUdpSocket.cpp.o
.PHONY : src/Client/QtBabel/QtUdpSocket.cpp.o

src/Client/QtBabel/QtUdpSocket.i: src/Client/QtBabel/QtUdpSocket.cpp.i

.PHONY : src/Client/QtBabel/QtUdpSocket.i

# target to preprocess a source file
src/Client/QtBabel/QtUdpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtUdpSocket.cpp.i
.PHONY : src/Client/QtBabel/QtUdpSocket.cpp.i

src/Client/QtBabel/QtUdpSocket.s: src/Client/QtBabel/QtUdpSocket.cpp.s

.PHONY : src/Client/QtBabel/QtUdpSocket.s

# target to generate assembly for a file
src/Client/QtBabel/QtUdpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/QtUdpSocket.cpp.s
.PHONY : src/Client/QtBabel/QtUdpSocket.cpp.s

src/Client/QtBabel/RingBuffer.o: src/Client/QtBabel/RingBuffer.cpp.o

.PHONY : src/Client/QtBabel/RingBuffer.o

# target to build an object file
src/Client/QtBabel/RingBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/RingBuffer.cpp.o
.PHONY : src/Client/QtBabel/RingBuffer.cpp.o

src/Client/QtBabel/RingBuffer.i: src/Client/QtBabel/RingBuffer.cpp.i

.PHONY : src/Client/QtBabel/RingBuffer.i

# target to preprocess a source file
src/Client/QtBabel/RingBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/RingBuffer.cpp.i
.PHONY : src/Client/QtBabel/RingBuffer.cpp.i

src/Client/QtBabel/RingBuffer.s: src/Client/QtBabel/RingBuffer.cpp.s

.PHONY : src/Client/QtBabel/RingBuffer.s

# target to generate assembly for a file
src/Client/QtBabel/RingBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/RingBuffer.cpp.s
.PHONY : src/Client/QtBabel/RingBuffer.cpp.s

src/Client/QtBabel/VoiceInterpreter.o: src/Client/QtBabel/VoiceInterpreter.cpp.o

.PHONY : src/Client/QtBabel/VoiceInterpreter.o

# target to build an object file
src/Client/QtBabel/VoiceInterpreter.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/VoiceInterpreter.cpp.o
.PHONY : src/Client/QtBabel/VoiceInterpreter.cpp.o

src/Client/QtBabel/VoiceInterpreter.i: src/Client/QtBabel/VoiceInterpreter.cpp.i

.PHONY : src/Client/QtBabel/VoiceInterpreter.i

# target to preprocess a source file
src/Client/QtBabel/VoiceInterpreter.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/VoiceInterpreter.cpp.i
.PHONY : src/Client/QtBabel/VoiceInterpreter.cpp.i

src/Client/QtBabel/VoiceInterpreter.s: src/Client/QtBabel/VoiceInterpreter.cpp.s

.PHONY : src/Client/QtBabel/VoiceInterpreter.s

# target to generate assembly for a file
src/Client/QtBabel/VoiceInterpreter.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/VoiceInterpreter.cpp.s
.PHONY : src/Client/QtBabel/VoiceInterpreter.cpp.s

src/Client/QtBabel/contact.o: src/Client/QtBabel/contact.cpp.o

.PHONY : src/Client/QtBabel/contact.o

# target to build an object file
src/Client/QtBabel/contact.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/contact.cpp.o
.PHONY : src/Client/QtBabel/contact.cpp.o

src/Client/QtBabel/contact.i: src/Client/QtBabel/contact.cpp.i

.PHONY : src/Client/QtBabel/contact.i

# target to preprocess a source file
src/Client/QtBabel/contact.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/contact.cpp.i
.PHONY : src/Client/QtBabel/contact.cpp.i

src/Client/QtBabel/contact.s: src/Client/QtBabel/contact.cpp.s

.PHONY : src/Client/QtBabel/contact.s

# target to generate assembly for a file
src/Client/QtBabel/contact.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/contact.cpp.s
.PHONY : src/Client/QtBabel/contact.cpp.s

src/Client/QtBabel/main.o: src/Client/QtBabel/main.cpp.o

.PHONY : src/Client/QtBabel/main.o

# target to build an object file
src/Client/QtBabel/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/main.cpp.o
.PHONY : src/Client/QtBabel/main.cpp.o

src/Client/QtBabel/main.i: src/Client/QtBabel/main.cpp.i

.PHONY : src/Client/QtBabel/main.i

# target to preprocess a source file
src/Client/QtBabel/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/main.cpp.i
.PHONY : src/Client/QtBabel/main.cpp.i

src/Client/QtBabel/main.s: src/Client/QtBabel/main.cpp.s

.PHONY : src/Client/QtBabel/main.s

# target to generate assembly for a file
src/Client/QtBabel/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/main.cpp.s
.PHONY : src/Client/QtBabel/main.cpp.s

src/Client/QtBabel/mainwindow.o: src/Client/QtBabel/mainwindow.cpp.o

.PHONY : src/Client/QtBabel/mainwindow.o

# target to build an object file
src/Client/QtBabel/mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/mainwindow.cpp.o
.PHONY : src/Client/QtBabel/mainwindow.cpp.o

src/Client/QtBabel/mainwindow.i: src/Client/QtBabel/mainwindow.cpp.i

.PHONY : src/Client/QtBabel/mainwindow.i

# target to preprocess a source file
src/Client/QtBabel/mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/mainwindow.cpp.i
.PHONY : src/Client/QtBabel/mainwindow.cpp.i

src/Client/QtBabel/mainwindow.s: src/Client/QtBabel/mainwindow.cpp.s

.PHONY : src/Client/QtBabel/mainwindow.s

# target to generate assembly for a file
src/Client/QtBabel/mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/Client/QtBabel/mainwindow.cpp.s
.PHONY : src/Client/QtBabel/mainwindow.cpp.s

src/Server/BabelServer.o: src/Server/BabelServer.cpp.o

.PHONY : src/Server/BabelServer.o

# target to build an object file
src/Server/BabelServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BabelServer.cpp.o
.PHONY : src/Server/BabelServer.cpp.o

src/Server/BabelServer.i: src/Server/BabelServer.cpp.i

.PHONY : src/Server/BabelServer.i

# target to preprocess a source file
src/Server/BabelServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BabelServer.cpp.i
.PHONY : src/Server/BabelServer.cpp.i

src/Server/BabelServer.s: src/Server/BabelServer.cpp.s

.PHONY : src/Server/BabelServer.s

# target to generate assembly for a file
src/Server/BabelServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BabelServer.cpp.s
.PHONY : src/Server/BabelServer.cpp.s

src/Server/BoostCircularBuffer.o: src/Server/BoostCircularBuffer.cpp.o

.PHONY : src/Server/BoostCircularBuffer.o

# target to build an object file
src/Server/BoostCircularBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostCircularBuffer.cpp.o
.PHONY : src/Server/BoostCircularBuffer.cpp.o

src/Server/BoostCircularBuffer.i: src/Server/BoostCircularBuffer.cpp.i

.PHONY : src/Server/BoostCircularBuffer.i

# target to preprocess a source file
src/Server/BoostCircularBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostCircularBuffer.cpp.i
.PHONY : src/Server/BoostCircularBuffer.cpp.i

src/Server/BoostCircularBuffer.s: src/Server/BoostCircularBuffer.cpp.s

.PHONY : src/Server/BoostCircularBuffer.s

# target to generate assembly for a file
src/Server/BoostCircularBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostCircularBuffer.cpp.s
.PHONY : src/Server/BoostCircularBuffer.cpp.s

src/Server/BoostConnexionAcceptor.o: src/Server/BoostConnexionAcceptor.cpp.o

.PHONY : src/Server/BoostConnexionAcceptor.o

# target to build an object file
src/Server/BoostConnexionAcceptor.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostConnexionAcceptor.cpp.o
.PHONY : src/Server/BoostConnexionAcceptor.cpp.o

src/Server/BoostConnexionAcceptor.i: src/Server/BoostConnexionAcceptor.cpp.i

.PHONY : src/Server/BoostConnexionAcceptor.i

# target to preprocess a source file
src/Server/BoostConnexionAcceptor.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostConnexionAcceptor.cpp.i
.PHONY : src/Server/BoostConnexionAcceptor.cpp.i

src/Server/BoostConnexionAcceptor.s: src/Server/BoostConnexionAcceptor.cpp.s

.PHONY : src/Server/BoostConnexionAcceptor.s

# target to generate assembly for a file
src/Server/BoostConnexionAcceptor.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostConnexionAcceptor.cpp.s
.PHONY : src/Server/BoostConnexionAcceptor.cpp.s

src/Server/BoostSerializer.o: src/Server/BoostSerializer.cpp.o

.PHONY : src/Server/BoostSerializer.o

# target to build an object file
src/Server/BoostSerializer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSerializer.cpp.o
.PHONY : src/Server/BoostSerializer.cpp.o

src/Server/BoostSerializer.i: src/Server/BoostSerializer.cpp.i

.PHONY : src/Server/BoostSerializer.i

# target to preprocess a source file
src/Server/BoostSerializer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSerializer.cpp.i
.PHONY : src/Server/BoostSerializer.cpp.i

src/Server/BoostSerializer.s: src/Server/BoostSerializer.cpp.s

.PHONY : src/Server/BoostSerializer.s

# target to generate assembly for a file
src/Server/BoostSerializer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSerializer.cpp.s
.PHONY : src/Server/BoostSerializer.cpp.s

src/Server/BoostSocket.o: src/Server/BoostSocket.cpp.o

.PHONY : src/Server/BoostSocket.o

# target to build an object file
src/Server/BoostSocket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSocket.cpp.o
.PHONY : src/Server/BoostSocket.cpp.o

src/Server/BoostSocket.i: src/Server/BoostSocket.cpp.i

.PHONY : src/Server/BoostSocket.i

# target to preprocess a source file
src/Server/BoostSocket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSocket.cpp.i
.PHONY : src/Server/BoostSocket.cpp.i

src/Server/BoostSocket.s: src/Server/BoostSocket.cpp.s

.PHONY : src/Server/BoostSocket.s

# target to generate assembly for a file
src/Server/BoostSocket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/BoostSocket.cpp.s
.PHONY : src/Server/BoostSocket.cpp.s

src/Server/Client.o: src/Server/Client.cpp.o

.PHONY : src/Server/Client.o

# target to build an object file
src/Server/Client.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Client.cpp.o
.PHONY : src/Server/Client.cpp.o

src/Server/Client.i: src/Server/Client.cpp.i

.PHONY : src/Server/Client.i

# target to preprocess a source file
src/Server/Client.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Client.cpp.i
.PHONY : src/Server/Client.cpp.i

src/Server/Client.s: src/Server/Client.cpp.s

.PHONY : src/Server/Client.s

# target to generate assembly for a file
src/Server/Client.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Client.cpp.s
.PHONY : src/Server/Client.cpp.s

src/Server/CommandHandler.o: src/Server/CommandHandler.cpp.o

.PHONY : src/Server/CommandHandler.o

# target to build an object file
src/Server/CommandHandler.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/CommandHandler.cpp.o
.PHONY : src/Server/CommandHandler.cpp.o

src/Server/CommandHandler.i: src/Server/CommandHandler.cpp.i

.PHONY : src/Server/CommandHandler.i

# target to preprocess a source file
src/Server/CommandHandler.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/CommandHandler.cpp.i
.PHONY : src/Server/CommandHandler.cpp.i

src/Server/CommandHandler.s: src/Server/CommandHandler.cpp.s

.PHONY : src/Server/CommandHandler.s

# target to generate assembly for a file
src/Server/CommandHandler.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/CommandHandler.cpp.s
.PHONY : src/Server/CommandHandler.cpp.s

src/Server/Main.o: src/Server/Main.cpp.o

.PHONY : src/Server/Main.o

# target to build an object file
src/Server/Main.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Main.cpp.o
.PHONY : src/Server/Main.cpp.o

src/Server/Main.i: src/Server/Main.cpp.i

.PHONY : src/Server/Main.i

# target to preprocess a source file
src/Server/Main.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Main.cpp.i
.PHONY : src/Server/Main.cpp.i

src/Server/Main.s: src/Server/Main.cpp.s

.PHONY : src/Server/Main.s

# target to generate assembly for a file
src/Server/Main.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Main.cpp.s
.PHONY : src/Server/Main.cpp.s

src/Server/Message.o: src/Server/Message.cpp.o

.PHONY : src/Server/Message.o

# target to build an object file
src/Server/Message.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Message.cpp.o
.PHONY : src/Server/Message.cpp.o

src/Server/Message.i: src/Server/Message.cpp.i

.PHONY : src/Server/Message.i

# target to preprocess a source file
src/Server/Message.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Message.cpp.i
.PHONY : src/Server/Message.cpp.i

src/Server/Message.s: src/Server/Message.cpp.s

.PHONY : src/Server/Message.s

# target to generate assembly for a file
src/Server/Message.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/Message.cpp.s
.PHONY : src/Server/Message.cpp.s

src/Server/SocketSelector.o: src/Server/SocketSelector.cpp.o

.PHONY : src/Server/SocketSelector.o

# target to build an object file
src/Server/SocketSelector.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/SocketSelector.cpp.o
.PHONY : src/Server/SocketSelector.cpp.o

src/Server/SocketSelector.i: src/Server/SocketSelector.cpp.i

.PHONY : src/Server/SocketSelector.i

# target to preprocess a source file
src/Server/SocketSelector.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/SocketSelector.cpp.i
.PHONY : src/Server/SocketSelector.cpp.i

src/Server/SocketSelector.s: src/Server/SocketSelector.cpp.s

.PHONY : src/Server/SocketSelector.s

# target to generate assembly for a file
src/Server/SocketSelector.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/Server/SocketSelector.cpp.s
.PHONY : src/Server/SocketSelector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... server_automoc"
	@echo "... client_automoc"
	@echo "... client_automoc.o"
	@echo "... client_automoc.i"
	@echo "... client_automoc.s"
	@echo "... server_automoc.o"
	@echo "... server_automoc.i"
	@echo "... server_automoc.s"
	@echo "... src/Client/QtBabel/BabelClient.o"
	@echo "... src/Client/QtBabel/BabelClient.i"
	@echo "... src/Client/QtBabel/BabelClient.s"
	@echo "... src/Client/QtBabel/Event.o"
	@echo "... src/Client/QtBabel/Event.i"
	@echo "... src/Client/QtBabel/Event.s"
	@echo "... src/Client/QtBabel/Message.o"
	@echo "... src/Client/QtBabel/Message.i"
	@echo "... src/Client/QtBabel/Message.s"
	@echo "... src/Client/QtBabel/QtCircularBuffer.o"
	@echo "... src/Client/QtBabel/QtCircularBuffer.i"
	@echo "... src/Client/QtBabel/QtCircularBuffer.s"
	@echo "... src/Client/QtBabel/QtGui.o"
	@echo "... src/Client/QtBabel/QtGui.i"
	@echo "... src/Client/QtBabel/QtGui.s"
	@echo "... src/Client/QtBabel/QtNet.o"
	@echo "... src/Client/QtBabel/QtNet.i"
	@echo "... src/Client/QtBabel/QtNet.s"
	@echo "... src/Client/QtBabel/QtUdpSocket.o"
	@echo "... src/Client/QtBabel/QtUdpSocket.i"
	@echo "... src/Client/QtBabel/QtUdpSocket.s"
	@echo "... src/Client/QtBabel/RingBuffer.o"
	@echo "... src/Client/QtBabel/RingBuffer.i"
	@echo "... src/Client/QtBabel/RingBuffer.s"
	@echo "... src/Client/QtBabel/VoiceInterpreter.o"
	@echo "... src/Client/QtBabel/VoiceInterpreter.i"
	@echo "... src/Client/QtBabel/VoiceInterpreter.s"
	@echo "... src/Client/QtBabel/contact.o"
	@echo "... src/Client/QtBabel/contact.i"
	@echo "... src/Client/QtBabel/contact.s"
	@echo "... src/Client/QtBabel/main.o"
	@echo "... src/Client/QtBabel/main.i"
	@echo "... src/Client/QtBabel/main.s"
	@echo "... src/Client/QtBabel/mainwindow.o"
	@echo "... src/Client/QtBabel/mainwindow.i"
	@echo "... src/Client/QtBabel/mainwindow.s"
	@echo "... src/Server/BabelServer.o"
	@echo "... src/Server/BabelServer.i"
	@echo "... src/Server/BabelServer.s"
	@echo "... src/Server/BoostCircularBuffer.o"
	@echo "... src/Server/BoostCircularBuffer.i"
	@echo "... src/Server/BoostCircularBuffer.s"
	@echo "... src/Server/BoostConnexionAcceptor.o"
	@echo "... src/Server/BoostConnexionAcceptor.i"
	@echo "... src/Server/BoostConnexionAcceptor.s"
	@echo "... src/Server/BoostSerializer.o"
	@echo "... src/Server/BoostSerializer.i"
	@echo "... src/Server/BoostSerializer.s"
	@echo "... src/Server/BoostSocket.o"
	@echo "... src/Server/BoostSocket.i"
	@echo "... src/Server/BoostSocket.s"
	@echo "... src/Server/Client.o"
	@echo "... src/Server/Client.i"
	@echo "... src/Server/Client.s"
	@echo "... src/Server/CommandHandler.o"
	@echo "... src/Server/CommandHandler.i"
	@echo "... src/Server/CommandHandler.s"
	@echo "... src/Server/Main.o"
	@echo "... src/Server/Main.i"
	@echo "... src/Server/Main.s"
	@echo "... src/Server/Message.o"
	@echo "... src/Server/Message.i"
	@echo "... src/Server/Message.s"
	@echo "... src/Server/SocketSelector.o"
	@echo "... src/Server/SocketSelector.i"
	@echo "... src/Server/SocketSelector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

